### ISSUE TITLE
Push notification not working when using uraban airship and layer 

### ISSUE THREAD

**Issue by rekhaagarwal** [layerhq/Atlas-Android#130]
I am using Urban airship for push notification and Layer for chat.(Both uses GCM key and sender id)
Currently I am facing one issue:
When I logout from my application and again login then I am not receiving push notification of urban air ship
As discussed with my server team, that might be due to Layer De - authentication on logout.( which is required)

Reply from urban airship team:
It does appear that the Layer logout is deregistering all GCM services.I'd recommend working with Layer to determine if there is a way to not have their SDK aggressively unregister all GCM services.

We have tried GCM as well FCM both in layer but same problem is happening.
 compile ('com.layer.atlas:layer-atlas:0.3.0'

**Comment by smpete** [comment]
Thanks for reporting this. I've filed an internal ticket to track this work: APPS-2713. We will update this GitHub issue once work is done. We do in fact call `FirebaseInstanceId.getInstance().deleteInstanceId()` and 'GoogleCloudMessaging.unregister` in older versions. Both of these should delete *all* tokens.

**Comment by rekhaagarwal** [comment]
hello @smpete 
Thanks for you reply.
Can you please update on above issue: APPS-2713. 
Currently I have upgraded to 'com.layer.atlas:layer-atlas:0.4.1'  and using FCM.
but again the issue is coming that on deauthentication, urban airship pushes are not being recieved as layer is de registering the all gcm servcies
And can you please tell me that is there any alternative function(fcm specific) in latest layer version for (setGcmRegistrationId()) which is deprecated now in latest layer version?

**Comment by smpete** [comment]
A fix for APPS-2713 is set to be released with the next version of the Layer SDK. I do not have a timeline for this but expect a release in a week or two.

You will have to use the `LayerClient.Options.alternateFcmSenderId()` to take advantage of the per sender ID token deletion. That will also be the function that replaced `setGcmRegistrationId`.

I'll close this ticket once the fix is released.

**Comment by rekhaagarwal** [comment]
@smpete thanks a lot.

regarding  some hack on app side to avoid this till we get proper fix:
In layer-atlas:0.3.0', whe we did setGcmRegistrationId(null, null) before calling deauthentication method( Util.deauthenticate(getLayerClient(), new Util.DeauthenticationCallback()), its worked for us.

but since this function has been deprecated in latest layer, can we put some kind of similarhack in latest layer?

**Comment by smpete** [comment]
I don't see a workaround being possible on the current SDK as the older `Gcm.unregister()` method doesn't seem to revoke the registration token. See the docs here: https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging#unregister(). That might be why the previous workaround worked.

**Comment by rekhaagarwal** [comment]
@smpete thanks for the prompt response. Will wait for fixed release then.

**Comment by rekhaagarwal** [comment]
@smpete can you please update on above issue. Any plan for the fix release?

**Comment by smpete** [comment]
@rekhaagarwal This was released in SDK `0.23.10`. The corresponding Atlas version for this is `0.4.4`. Make sure you supply the Layer SDK with an alternate sender ID rather than implicitly loading one from the `google-services.json` file (it can be the same sender ID). This is needed so we know what token to revoke.

Also remember that you can see the current release notes for the SDK here: https://github.com/layerhq/releases-android/releases

**Comment by rekhaagarwal** [comment]
@smpete thanks a lot!. Will make the latest release and make necessary changes.
Regarding "Make sure you supply the Layer SDK with an alternate sender ID rather than implicitly loading one from the google-services.json file ", lets say my FCM sender id is A(defined in google-services.json), and UA sender is B.
Then I should set alternated sender id to A or B or both?
